scisforum/chats/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, Length


class MessageForm(FlaskForm):
    body = StringField('', validators=[DataRequired(), Length(min=1)], render_kw={'autofocus': True})

scisforum/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=2, max=100)])
    content = TextAreaField('Content', validators=[DataRequired(), Length(min=10, max=1000)])
    submit = SubmitField('Post')

scisforum/calendar/routes.py
import dateutil.parser as dt
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from scisforum import db
from scisforum.models import Event, User

calendar = Blueprint('calendar', __name__)


@calendar.route('/calendar', methods=['GET', 'POST'])
@login_required
def calendar_view():
    events = Event.query.join(User, User.id==Event.creator_id).add_columns(Event.id, Event.title, Event.start_time, Event.end_time, User.username).all()
    return render_template('calendar.html', title='Calendar', events=events)


@calendar.route("/insert_event", methods=['GET', 'POST'])
@login_required
def insert_event():
    if current_user.access == False:
        abort(403)
    if request.method == 'POST':
        title = request.form['title']
        start_time = dt.parse(request.form['start'])
        end_time = dt.parse(request.form['end'])
        old_event = Event.query.filter_by(title = title, start_time = start_time, end_time = end_time).first()
        if not(old_event):
            event = Event(title=title, start_time=start_time, end_time=end_time, creator_id=current_user.id)
            db.session.add(event)
            db.session.commit()
            flash('Event Created.', 'success')
            return redirect(url_for('calendar.calendar_view'))



@calendar.route("/update_event", methods=['GET', 'POST'])
@login_required
def update_event():
    if current_user.access == False:
        abort(403)
    if request.method == 'POST':
        title = request.form['title']
        start_time = dt.parse(request.form['start'])
        end_time = dt.parse(request.form['end'])
        id = request.form['id']
        event = Event.query.get_or_404(id)
        if event.creator_id != current_user.id:
            abort(403)
        event.title = title
        event.start_time = start_time
        event.end_time = end_time
        db.session.commit()
        flash('Event updated.', 'success')
        return redirect(url_for('calendar.calendar_view'))


@calendar.route("/delete_event", methods=['GET', 'POST'])
@login_required
def delete_event():
    if current_user.access == False:
        abort(403)
    if request.method == 'POST':
        id = request.form['id']
        event = Event.query.get_or_404(id)
        if event.creator_id != current_user.id:
            abort(403)
        db.session.delete(event)
        db.session.commit()
        flash('Event deleted.', 'success')
        return redirect(url_for('calendar.calendar_view'))

scisforum/chats/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_required
from sqlalchemy import or_, and_
from scisforum import db
from scisforum.models import User, Message
from scisforum.chats.forms import MessageForm
from scisforum.profanity_checker import predict_prob

chats = Blueprint('chats', __name__)


@chats.route('/chatting/<string:username>', methods=['GET', 'POST'])
@login_required
def chatting(username):
    form = MessageForm(request.form)
    user = User.query.filter_by(username=username).first_or_404()
    if request.method == 'POST':
        if predict_prob([form.body.data]) > 0.4:
            flash('Your text contains inappropriate words. Please filter out them.', 'danger')
            return redirect(url_for('chats.chatting', username=username))
        message = Message(msg_by_id=current_user.id, msg_to_id=user.id, body=form.body.data)
        db.session.add(message)
        db.session.commit()
    existing = Message.query.join(User, or_(User.id == Message.msg_by_id, User.id == Message.msg_to_id)).add_columns(User.username).filter(or_(Message.msg_by_id == current_user.id, Message.msg_to_id == current_user.id)).order_by(Message.msg_time.desc())
    unique = []
    for user in existing:
        if user.username != current_user.username and user.username not in unique:
            unique.append(user.username)
    users = User.query.filter(User.username.notin_([*unique, current_user.username]))
    for user in users:
        unique.append(user.username)
    return render_template('chat_room.html', users=unique, form=form, receiver=username)


@chats.route('/chats/<string:username>', methods=['GET', 'POST'])
@login_required
def chats_view(username):
    user = User.query.filter_by(username=username).first_or_404()
    messages = Message.query.filter(or_((and_(Message.msg_by_id==user.id, Message.msg_to_id==current_user.id)), (and_(Message.msg_by_id==current_user.id, Message.msg_to_id==user.id))))
    return render_template('chats.html', title='Chat', chats=messages)

scisforum/main/routes.py
from flask import render_template, request, Blueprint, flash, redirect, url_for
from flask_login import current_user
from scisforum.models import Post
from scisforum.main.utils import send_message, reply_message
main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route('/about')
def about():
    return render_template('about.html', title='About')


@main.route('/contact', methods=['GET', 'POST'])
def contact():
    if request.method == 'POST':
        message = request.form['message']
        if(message == ''):
            flash('Message is empty', 'warning')
            return redirect(url_for('main.home'))
        send_message(current_user.email, message)
        reply_message(current_user.email)
        flash('Message Sent', 'info')
    return redirect(url_for('main.home'))


@main.route('/search', methods=['GET'])
def search():
    keyword = request.args.get('search')
    page = request.args.get('page', 1, type=int)
    if keyword is None:
        return redirect(url_for('main.home'))
    keyword = keyword.lower()
    posts = Post.query.filter(Post.title.like(f'%{keyword}%')).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts, keyword=keyword)

scisforum/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from scisforum import db
from scisforum.models import Post
from scisforum.posts.forms import PostForm
from scisforum.profanity_checker import predict_prob

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        if predict_prob([form.content.data]) > 0.4 or predict_prob([form.title.data]) > 0.4:
            flash('Your post contains inappropriate words. Please filter out them.', 'danger')
            return redirect(url_for('posts.new_post'))
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created.', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        if predict_prob([form.content.data]) > 0.4 or predict_prob([form.title.data]) > 0.4:
            flash('Your post contains inappropriate words. Please filter out them.', 'danger')
            return redirect(url_for('posts.new_post'))
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated.', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted.', 'success')
    return redirect(url_for('main.home'))

scisforum/users/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from scisforum import db, bcrypt
from scisforum.models import User, Post
from scisforum.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm, FaceLoginForm)
from scisforum.users.utils import save_picture, send_reset_email, image_to_encoding, verify_face

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created. You can now login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login')
def login():
    return render_template('login.html', title='Login')


@users.route('/login_password', methods=['GET', 'POST'])
def login_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password.', 'danger')
    return render_template('login_password.html', title='Login', form=form)


@users.route('/login_face', methods=['GET', 'POST'])
def login_face():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = FaceLoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None:
            flash('Check username and try again.', 'danger')
            return redirect(url_for('users.login_face'))
        if user.face_access == False:
            flash('Your face is not yet registered. Please register in account.', 'danger')
            return redirect(url_for('users.login_password'))
        if user and verify_face(user.encoding_file, request.form['face_img']):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Face not recognized.', 'danger')
    return render_template('login_face.html', title='Login', form=form)


@users.route("/<int:user_id>/update", methods=['GET', 'POST'])
@login_required
def update_face(user_id):
    user = User.query.get_or_404(user_id)
    if user_id != user.id:
        abort(403)
    if request.method == 'POST':
        try:
            encoding_file = image_to_encoding(request.form['face_img'], user.username)
            user.face_access = True
            user.encoding_file = encoding_file
            db.session.add(user)
            db.session.commit()
            flash(f'Face data updated successfully.', 'success')
        except:
            flash('Face not recognized.', 'danger')
        return redirect(url_for('users.account'))


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.email = form.email.data
        db.session.add(current_user)
        db.session.commit()
        flash('Your account has been updated.', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

scisforum/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='dark-mode.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  {% block head %}
  {% endblock %}
  {% if title %}
  <title>{{ title }}</title>
  {% else %}
  <title>SCIS Forum</title>
  {% endif %}
</head>

<body onload="init_clock()">
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4 dark-heading" href="/">SCIS Forum</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            <form action="{{url_for('main.search')}}" method="GET" class="form-inline">
              <div class="form-row ml-1">
                <input type="text" class="form-control ml-2 mr-2" id="search" placeholder="Search..." name="search">
                <button type="submit" class="btn button-outline">Search</button>
              </div>
            </form>
          </div>
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('calendar.calendar_view') }}">Calendar</a>
            <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
            <a class="nav-item nav-link" href="{{ url_for('chats.chatting', username=current_user.username)}}">Chats</a>
            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav> 
  </header>
  <div role="main" class="container">
    <div class="row">
      <div class="col-md-8 mb-2">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
      </div>
      <div class="col-md-4">
        <div class="content-section">
          <p>Works best in a PC. We are working on mobile version.</p>
        </div>
        <div class="content-section">
          <div class="datetime text-center">
            <div class="date">
              <span id="dayname">Day</span>,
              <span id="month">Month</span>
              <span id="daynum">00</span>,
              <span id="year">Year</span>
            </div>
            <div class="time">
              <span id="hour">00</span>:
              <span id="minutes">00</span>:
              <span id="seconds">00</span>
              <span id="period">AM</span>
            </div>
          </div>
        </div>
        <div class="content-section">
          <div class="form-check">
            <label class="switch">
              <input type="checkbox" id="darkSwitch">
              <span class="slider round"></span>
            </label>
            <label>Dark Mode</label>

          </div>
        </div>
        <div class="content-section">
          <h3>Our Sidebar</h3>
          <p class='text-muted'>What's new?
            <ul class="list-group">
              <li class="list-group-item list-group-item-light">Search post based on title</li>
              <li class="list-group-item list-group-item-light">Drag and drop in calendar</li>
            </ul>
          </p>
        </div>
        {% if current_user.is_authenticated %}
        <div class="content-section">
          <h3>Any suggestions?</h3>
          <form action="{{ url_for('main.contact') }}" method="POST" onsubmit="validate_contact()" id="contact_form">
            <div class="mb-3">
              <textarea class="form-control" name="message" id="message" rows="5" required></textarea>
              <small id="message_error_block" class="text-danger"></small>
            </div>
            <div class="mb-3 text-center">
              <button type="submit" class="btn button-outline">Submit</button>
            </div>
          </form>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
  <script src="{{ url_for('static', filename='scripts/clock.js') }}"></script>
  <script src="{{ url_for('static', filename='scripts/dark-mode-switch.js') }}"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
    crossorigin="anonymous"></script>
  <script src="{{ url_for('static', filename='scripts/contact-form-validation.js') }}"></script>
  {% block script %}
  {% endblock %}
</body>

</html>

scisforum/templates/calendar.html
{% extends "base.html" %}

{% block head %}
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.css" /> -->
<link href="{{ url_for('static', filename='calendar.css') }}" rel='stylesheet' />
{% endblock %}

{% block content %}
<div class="container">
  <div id="calendar"></div>
</div>

<div class="modal fade" id="insert_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content dark-modal">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Event Title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="" method="POST">
          <div class="mb-3">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="Enter Event title">
            <small id="title_error_block" class="text-danger"></small>
          </div>
          <div class="mb-3">
            <label for="start_time">Start Time</label>
            <input type="datetime-local" class="form-control" id="start_time" name="start_time">
            <small id="start_error_block" class="text-danger"></small>
          </div>
          <div class="mb-3">
            <label for="end_time">End Time</label>
            <input type="datetime-local" class="form-control" id="end_time" name="end_time">
            <small id="end_error_block" class="text-danger"></small>
          </div>
          <button type="submit" class="btn button-outline">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="delete_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content dark-modal">
      <div class="modal-header">
        <h5 class="modal-title" id="event_title"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h5 id="creator">Created by: </h5>
        <h6 id="time"></h6>
      </div>
      {%if current_user.access %}
        <div class="modal-footer">
          <form action="" method="POST">
            <button type="submit" class="btn button-outline" id="delete">Delete</button>
          </form>
        </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script src="{{ url_for('static', filename='scripts/main.js') }}"></script>
<!-- <script src='http://fullcalendar.io/js/fullcalendar-2.1.1/lib/moment.min.js'></script> -->
<script src='https://cdn.jsdelivr.net/npm/moment@2.27.0/min/moment.min.js'></script>
 <!-- <script src='http://fullcalendar.io/js/fullcalendar-2.1.1/lib/jquery.min.js'></script>
<script src="http://fullcalendar.io/js/fullcalendar-2.1.1/lib/jquery-ui.custom.min.js"></script>  -->
<script src='https://cdn.jsdelivr.net/npm/@fullcalendar/moment@5.5.0/main.global.min.js'></script>

<!-- <script src='http://fullcalendar.io/js/fullcalendar-2.1.1/fullcalendar.min.js'></script> -->
<script>
  function toBool(){
    if('{{current_user.access}}' === 'True'){
      return true;
    }
    return false;
  }

  document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');

    var calendar = new FullCalendar.Calendar(calendarEl, {
      editable: true,
      headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right:''
      },
      displayEventTime : false,
      events: [
        {% for row in events %}
          { id : '{{row.id}}', title : '{{row.title}}', start : '{{row.start_time}}', end : '{{row.end_time}}', creator : '{{row.username}}'}, 
        {% endfor %}
      ],
      dayMaxEvents: 1,
      selectable: true,
      select: function(start, allDay) {
        if(toBool()){
          let end_time = start.end;
          start=moment(start.start).format('YYYY-MM-DDTHH:mm'); 
          let end=moment(end_time).format('YYYY-MM-DDTHH:mm');
          $("#start_time").val(start);
          $("#end_time").val(end);
          $("#insert_modal").modal("show");
          
          $( "#insert_modal" ).submit(function( e ) {
            e.preventDefault();
            var title = $('#title').val().trim();
            var start_time = $('#start_time').val();
            var end_time = $('#end_time').val();
            var flag = 0;
            start=moment(start_time).format('YYYY-MM-DDTHH:mm:ssZ'); 
            end=moment(end_time).format('YYYY-MM-DDTHH:mm:ssZ');

            if(!title){
              $('#title_error_block').html('Enter the Event Name');
              flag = 1;
            }
            if(moment(start_time).toDate().getTime() > moment(end_time).toDate().getTime()){
              $('#end_error_block').html('End Time is less than Start Time');
              flag = 1;
            }

            if(!flag) {
              $.ajax({
                url: "{{ url_for('calendar.insert_event') }}",
                type: "POST",
                data: {title:title, start:start, end:end},
                success: function(){
                  $("#insert_modal").modal("hide");
                  calendar.render();
                  window.location.replace("{{ url_for('calendar.calendar_view') }}");
                },
                statusCode: {
                  403: function () {
                      $("#insert_modal").modal("hide");
                      alert('Not Authorized');
                      //window.location.replace("url_for(errors.app_errorhandler(404))");
                  }
                }
              })
            }
          });
        }
      },
      editable: toBool(),
      eventDrop: function(event) {
        start = moment(event.event._instance.range.start).format('YYYY-MM-DDTHH:mm:ssZ'); 
        end = moment(event.event._instance.range.start).format('YYYY-MM-DDTHH:mm:ssZ');
        var title = event.event._def.title;
        var id = event.event._def.publicId;  
        $.ajax({
          url: "{{ url_for('calendar.update_event') }}",
          type: "POST",
          data: {title:title, start:start, end:end, id:id},
          success: function() {
            calendar.render();
          },
          statusCode: {
            403: function () {
                alert('Not Authorized');
                //window.location.replace("url_for(errors.app_errorhandler(404))");
            }
          }
        });
      },
      eventClick: function(event) {
        var start = moment(event.event._instance.range.start).format('DD/MM/YYYY HH:mm:ss'); 
        var end = moment(event.event._instance.range.end).format('DD/MM/YYYY HH:mm:ss');
        $('#event_title').html(event.event._def.title);
        $('#creator').html(`Created By: ${event.event._def.extendedProps.creator}`);
        $('#time').html(`Time: ${start} - ${end}`);
        $('#delete_modal').modal("show");

        $( "#delete_modal" ).submit(function( e) {
          e.preventDefault();
          var id = event.event._def.publicId;
          $.ajax({
            url: "{{ url_for('calendar.delete_event') }}",
            type: "POST",
            data: {id:id},
            success: function() {
              calendar.render();
              $('#delete_modal').modal("hide");
              window.location.replace("{{ url_for('calendar.calendar_view') }}");
            },
            statusCode: {
              403: function () {
                  alert('Not Authorized');
                  //window.location.replace("url_for(errors.app_errorhandler(404))");
              }
            }
          })
        });
      }
    });

    calendar.render();
  });

</script>
{% endblock %}

scisforum/templates/chats.html
{% for message in chats %}
{% if (message.msg_by_id or message.msg_to_id) != current_user.id %}
    <div class="from">
        <p>
            <span class="from-text"> {{ message.body }}</span>
        </p>
    </div>
{% else %}
    <div class="to">
        <p>
            <span class="to-text"> {{ message.body }}</span>
        </p>
    </div>
{% endif %}
{% endfor %}

scisforum/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="mb-3">
                {{ form.title.label(class="form-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.content.label(class="form-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg", rows="5") }}
                {% endif %}
            </div>
            {{ form.submit(class="btn btn-outline-info button-outline") }}
        </fieldset>
    </form>
</div>
{% endblock content %}